import { MigrationInterface, QueryRunner } from "typeorm";

export class TransitionServiceChanges1754546978924 implements MigrationInterface {
    name = 'TransitionServiceChanges1754546978924'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`account_renewal_requests\` (\`id\` int NOT NULL AUTO_INCREMENT, \`account_renewal_request_no\` varchar(255) NOT NULL, \`request_type\` enum ('owner', 'tenant', 'hho_company', 'hho_owner') NOT NULL, \`status\` enum ('open', 'rfi', 'user-cancelled', 'cancel', 'approve') NOT NULL, \`move_in_date\` date NULL, \`move_out_date\` date NULL, \`comments\` text NULL, \`additional_info\` text NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`move_in_request_id\` int NULL, \`parent_account_renewal_id\` int NULL, \`user_id\` int NULL, \`unit_id\` int NOT NULL, UNIQUE INDEX \`IDX_3d26416a9362b3cc16f7311c45\` (\`account_renewal_request_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`request_details_hho_company\` (\`id\` varchar(36) NOT NULL, \`company_name\` varchar(255) NOT NULL, \`trade_license_number\` varchar(100) NULL, \`company_address\` varchar(255) NULL, \`company_phone\` varchar(20) NULL, \`company_email\` varchar(255) NULL, \`power_of_attorney_number\` varchar(100) NULL, \`attorney_name\` varchar(255) NULL, \`attorney_phone\` varchar(20) NULL, \`ejari_number\` varchar(100) NULL, \`dtcm_permit_number\` varchar(100) NULL, \`emergency_contact_name\` varchar(255) NULL, \`relationship\` varchar(100) NULL, \`comments\` text NULL, \`monthly_rent\` double(12,2) NULL, \`security_deposit\` double(12,2) NULL, \`maintenance_fee\` double(12,2) NULL, \`currency\` varchar(10) NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_details_hho_owner\` (\`id\` varchar(36) NOT NULL, \`owner_first_name\` varchar(100) NOT NULL, \`owner_last_name\` varchar(100) NOT NULL, \`attorney_first_name\` varchar(100) NULL, \`attorney_last_name\` varchar(100) NULL, \`email\` varchar(255) NOT NULL, \`dial_code\` varchar(10) NOT NULL, \`phone_number\` varchar(20) NOT NULL, \`nationality\` varchar(100) NOT NULL, \`date_of_birth\` date NULL, \`emergency_contact_dial_code\` varchar(10) NULL, \`emergency_contact_number\` varchar(20) NULL, \`adults\` int NOT NULL DEFAULT '0', \`children\` int NOT NULL DEFAULT '0', \`household_staffs\` int NOT NULL DEFAULT '0', \`pets\` int NOT NULL DEFAULT '0', \`emirates_id_number\` varchar(100) NULL, \`passport_number\` varchar(100) NULL, \`visa_number\` varchar(100) NULL, \`power_of_attorney_number\` varchar(100) NULL, \`attorney_name\` varchar(255) NULL, \`attorney_phone\` varchar(20) NULL, \`ejari_number\` varchar(100) NULL, \`dtcm_permit_number\` varchar(100) NULL, \`emergency_contact_name\` varchar(255) NULL, \`relationship\` varchar(100) NULL, \`comments\` text NULL, \`monthly_rent\` double(12,2) NULL, \`security_deposit\` double(12,2) NULL, \`maintenance_fee\` double(12,2) NULL, \`currency\` varchar(10) NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_details_tenant\` (\`id\` varchar(36) NOT NULL, \`first_name\` varchar(100) NOT NULL, \`last_name\` varchar(100) NOT NULL, \`email\` varchar(255) NOT NULL, \`dial_code\` varchar(10) NOT NULL, \`phone_number\` varchar(20) NOT NULL, \`nationality\` varchar(100) NOT NULL, \`date_of_birth\` date NULL, \`emergency_contact_dial_code\` varchar(10) NULL, \`emergency_contact_number\` varchar(20) NULL, \`adults\` int NOT NULL DEFAULT '0', \`children\` int NOT NULL DEFAULT '0', \`household_staffs\` int NOT NULL DEFAULT '0', \`pets\` int NOT NULL DEFAULT '0', \`emirates_id_number\` varchar(100) NULL, \`passport_number\` varchar(100) NULL, \`visa_number\` varchar(100) NULL, \`power_of_attorney_number\` varchar(100) NULL, \`attorney_name\` varchar(255) NULL, \`attorney_phone\` varchar(20) NULL, \`ejari_number\` varchar(100) NULL, \`dtcm_permit_number\` varchar(100) NULL, \`emergency_contact_name\` varchar(255) NULL, \`relationship\` varchar(100) NULL, \`comments\` text NULL, \`monthly_rent\` double(12,2) NULL, \`security_deposit\` double(12,2) NULL, \`maintenance_fee\` double(12,2) NULL, \`currency\` varchar(10) NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_details_owner\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`emergency_contact_dial_code\` varchar(10) NULL, \`emergency_contact_number\` varchar(20) NULL, \`adults\` int NOT NULL DEFAULT '0', \`children\` int NOT NULL DEFAULT '0', \`household_staffs\` int NOT NULL DEFAULT '0', \`pets\` int NOT NULL DEFAULT '0', \`emirates_id_number\` varchar(100) NULL, \`passport_number\` varchar(100) NULL, \`visa_number\` varchar(100) NULL, \`company_name\` varchar(255) NULL, \`trade_license_number\` varchar(100) NULL, \`company_address\` varchar(255) NULL, \`company_phone\` varchar(20) NULL, \`company_email\` varchar(255) NULL, \`power_of_attorney_number\` varchar(100) NULL, \`attorney_name\` varchar(255) NULL, \`attorney_phone\` varchar(20) NULL, \`ejari_number\` varchar(100) NULL, \`dtcm_permit_number\` varchar(100) NULL, \`emergency_contact_name\` varchar(255) NULL, \`relationship\` varchar(100) NULL, \`comments\` text NULL, \`monthly_rent\` double(12,2) NULL, \`security_deposit\` double(12,2) NULL, \`maintenance_fee\` double(12,2) NULL, \`currency\` varchar(10) NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_logs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`request_type\` enum ('owner', 'tenant', 'hho_company', 'hho_owner') NOT NULL, \`account_renewal_request_details_id\` bigint NULL, \`document_id\` bigint NULL, \`status\` enum ('open', 'rfi', 'user-cancelled', 'cancel', 'approve') NOT NULL, \`changes\` text NULL, \`action_by\` enum ('community-admin', 'super-admin', 'system', 'user') NOT NULL, \`details\` json NULL, \`timestamp\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`comments\` varchar(255) NULL, \`move_in_request_id\` int NULL, \`account_renewal_request_id\` int NULL, \`user_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_documents\` (\`id\` int NOT NULL AUTO_INCREMENT, \`document_type\` enum ('passport-front', 'passport-back', 'emirates-id-front', 'emirates-id-back', 'unit-permit', 'company-trade-license', 'ejari', 'title-deed', 'other') NOT NULL, \`expiry_date\` date NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`created_by\` int NOT NULL, \`updated_by\` int NOT NULL, \`user_id\` int NULL, \`account_renewal_request_id\` int NULL, \`file_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`move_out_requests\` (\`id\` int NOT NULL AUTO_INCREMENT, \`move_out_request_no\` varchar(255) NOT NULL, \`request_type\` enum ('owner', 'tenant', 'hho_company', 'hho_owner') NOT NULL, \`status\` enum ('open', 'rfi', 'user-cancelled', 'cancel', 'approve') NOT NULL, \`move_out_date\` date NULL, \`comments\` text NULL, \`additional_info\` text NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`user_id\` int NULL, \`unit_id\` int NOT NULL, \`move_in_request_id\` int NULL, \`account_renewal_request_id\` int NULL, UNIQUE INDEX \`IDX_567cfd75abc362fd6a9c17b5a2\` (\`move_out_request_no\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` ADD CONSTRAINT \`FK_492bd4fead75cf7276051e44354\` FOREIGN KEY (\`move_in_request_id\`) REFERENCES \`move_in_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` ADD CONSTRAINT \`FK_cd55433a7edfe374dc56f0d686e\` FOREIGN KEY (\`parent_account_renewal_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` ADD CONSTRAINT \`FK_9ddc538bd342516b19e61faeed7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` ADD CONSTRAINT \`FK_a826a256df26f131c91b7718c3d\` FOREIGN KEY (\`unit_id\`) REFERENCES \`units\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`request_details_hho_company\` ADD CONSTRAINT \`FK_8f4d823b510f773a6373fd4bc8a\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_hho_owner\` ADD CONSTRAINT \`FK_6bef2837b2839572e419d5bf3b7\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_tenant\` ADD CONSTRAINT \`FK_0465154880dd49fdbc4b15ded75\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_owner\` ADD CONSTRAINT \`FK_1ee748f5d1a02bcecd5b0f480d9\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_logs\` ADD CONSTRAINT \`FK_389f42c5cb29730278fca8303d1\` FOREIGN KEY (\`move_in_request_id\`) REFERENCES \`move_in_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_logs\` ADD CONSTRAINT \`FK_de83c3b65970370353f66f163b9\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_logs\` ADD CONSTRAINT \`FK_825a613a3fd4f43bb2e760e2a7b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_documents\` ADD CONSTRAINT \`FK_068dc12b6f329f4b5c90f0a7a37\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_documents\` ADD CONSTRAINT \`FK_e6461ada36a0be3d6d4d9a1017e\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_documents\` ADD CONSTRAINT \`FK_473cf15b7bb90a17adfc0573ea7\` FOREIGN KEY (\`file_id\`) REFERENCES \`file_uploads\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` ADD CONSTRAINT \`FK_cf9dd11105510dcf407482028ec\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` ADD CONSTRAINT \`FK_9e53f98ac2a9aee9177af736bcc\` FOREIGN KEY (\`unit_id\`) REFERENCES \`units\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` ADD CONSTRAINT \`FK_9bb86dfb57d016297747939079c\` FOREIGN KEY (\`move_in_request_id\`) REFERENCES \`move_in_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` ADD CONSTRAINT \`FK_13a14b925eec13b86ef478df878\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` DROP FOREIGN KEY \`FK_13a14b925eec13b86ef478df878\``);
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` DROP FOREIGN KEY \`FK_9bb86dfb57d016297747939079c\``);
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` DROP FOREIGN KEY \`FK_9e53f98ac2a9aee9177af736bcc\``);
        await queryRunner.query(`ALTER TABLE \`move_out_requests\` DROP FOREIGN KEY \`FK_cf9dd11105510dcf407482028ec\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_documents\` DROP FOREIGN KEY \`FK_473cf15b7bb90a17adfc0573ea7\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_documents\` DROP FOREIGN KEY \`FK_e6461ada36a0be3d6d4d9a1017e\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_documents\` DROP FOREIGN KEY \`FK_068dc12b6f329f4b5c90f0a7a37\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_logs\` DROP FOREIGN KEY \`FK_825a613a3fd4f43bb2e760e2a7b\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_logs\` DROP FOREIGN KEY \`FK_de83c3b65970370353f66f163b9\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_logs\` DROP FOREIGN KEY \`FK_389f42c5cb29730278fca8303d1\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_owner\` DROP FOREIGN KEY \`FK_1ee748f5d1a02bcecd5b0f480d9\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_tenant\` DROP FOREIGN KEY \`FK_0465154880dd49fdbc4b15ded75\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_hho_owner\` DROP FOREIGN KEY \`FK_6bef2837b2839572e419d5bf3b7\``);
        await queryRunner.query(`ALTER TABLE \`request_details_hho_company\` DROP FOREIGN KEY \`FK_8f4d823b510f773a6373fd4bc8a\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` DROP FOREIGN KEY \`FK_a826a256df26f131c91b7718c3d\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` DROP FOREIGN KEY \`FK_9ddc538bd342516b19e61faeed7\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` DROP FOREIGN KEY \`FK_cd55433a7edfe374dc56f0d686e\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_requests\` DROP FOREIGN KEY \`FK_492bd4fead75cf7276051e44354\``);
        await queryRunner.query(`DROP INDEX \`IDX_567cfd75abc362fd6a9c17b5a2\` ON \`move_out_requests\``);
        await queryRunner.query(`DROP TABLE \`move_out_requests\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_documents\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_logs\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_details_owner\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_details_tenant\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_details_hho_owner\``);
        await queryRunner.query(`DROP TABLE \`request_details_hho_company\``);
        await queryRunner.query(`DROP INDEX \`IDX_3d26416a9362b3cc16f7311c45\` ON \`account_renewal_requests\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_requests\``);
    }

}