import { MigrationInterface, QueryRunner } from "typeorm";

export class TransitionServiceChanges1761112171830 implements MigrationInterface {
    name = 'TransitionServiceChanges1761112171830'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_details_hho_company\` (\`id\` int NOT NULL AUTO_INCREMENT, \`lease_contract_end_date\` date NULL, \`dtcm_permit_end_date\` date NULL, \`permit_expiry\` date NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_details_tenant\` (\`id\` int NOT NULL AUTO_INCREMENT, \`tenancy_contract_end_date\` date NULL, \`adults\` int NOT NULL DEFAULT '0', \`children\` int NOT NULL DEFAULT '0', \`household_staffs\` int NOT NULL DEFAULT '0', \`pets\` int NOT NULL DEFAULT '0', \`determination_comments\` text NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_details_hho_owner\` (\`id\` int NOT NULL AUTO_INCREMENT, \`dtcm_permit_end_date\` date NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`account_renewal_request_details_owner\` (\`id\` bigint NOT NULL AUTO_INCREMENT, \`emergency_contact_dial_code\` varchar(10) NULL, \`emergency_contact_number\` varchar(20) NULL, \`adults\` int NOT NULL DEFAULT '0', \`children\` int NOT NULL DEFAULT '0', \`household_staffs\` int NOT NULL DEFAULT '0', \`pets\` int NOT NULL DEFAULT '0', \`emirates_id_number\` varchar(100) NULL, \`passport_number\` varchar(100) NULL, \`visa_number\` varchar(100) NULL, \`company_name\` varchar(255) NULL, \`trade_license_number\` varchar(100) NULL, \`company_address\` varchar(255) NULL, \`company_phone\` varchar(20) NULL, \`company_email\` varchar(255) NULL, \`power_of_attorney_number\` varchar(100) NULL, \`attorney_name\` varchar(255) NULL, \`attorney_phone\` varchar(20) NULL, \`ejari_number\` varchar(100) NULL, \`dtcm_permit_number\` varchar(100) NULL, \`emergency_contact_name\` varchar(255) NULL, \`relationship\` varchar(100) NULL, \`comments\` text NULL, \`monthly_rent\` double(12,2) NULL, \`security_deposit\` double(12,2) NULL, \`maintenance_fee\` double(12,2) NULL, \`currency\` varchar(10) NULL, \`created_by\` bigint NOT NULL, \`updated_by\` bigint NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`account_renewal_request_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_hho_company\` ADD CONSTRAINT \`FK_db6b5411557b108002c3c8ddb77\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_tenant\` ADD CONSTRAINT \`FK_0465154880dd49fdbc4b15ded75\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_hho_owner\` ADD CONSTRAINT \`FK_6bef2837b2839572e419d5bf3b7\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_owner\` ADD CONSTRAINT \`FK_1ee748f5d1a02bcecd5b0f480d9\` FOREIGN KEY (\`account_renewal_request_id\`) REFERENCES \`account_renewal_requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_owner\` DROP FOREIGN KEY \`FK_1ee748f5d1a02bcecd5b0f480d9\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_hho_owner\` DROP FOREIGN KEY \`FK_6bef2837b2839572e419d5bf3b7\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_tenant\` DROP FOREIGN KEY \`FK_0465154880dd49fdbc4b15ded75\``);
        await queryRunner.query(`ALTER TABLE \`account_renewal_request_details_hho_company\` DROP FOREIGN KEY \`FK_db6b5411557b108002c3c8ddb77\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_details_owner\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_details_hho_owner\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_details_tenant\``);
        await queryRunner.query(`DROP TABLE \`account_renewal_request_details_hho_company\``);
    }

}
